-- Re-ejecutable: mismo backfill que
-- supabase/migrations/20261007120000_community_category_guess_backfill.sql
--
-- NO correr contra producción desde CI/agente. Tras review:
--   psql "$DATABASE_URL" -f supabase/migrations/20261007120000_community_category_guess_backfill.sql
--
-- Distribución:
--   select coalesce(category_guess, '(null)') as cat, count(*)
--   from public.community_posts
--   group by 1 order by 2 desc;
